
name: task

on:
  issues:
    types: [opened]

jobs:
  task:
    name: update dynamic info
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run
        run: |
          python ./Main.py "${{ secrets.username }}" "${{ secrets.password }}" problemsetQuestionsDynamicInfos
      - name: update github
        run: |
          git diff
          git config --global user.email "yanzeyu2019@gmail.com"
          git config --global user.name "Gabriel"
          git add README.md
          git commit -m "Github Action Auto Updated"
          git push
      
